c = """byyqcwcszchhnchryhhnchjnfefhnchjnyk fhnchjxjyzshfdfepyzfpyxbydffdfepyzf
pyxqzyafdfepyzfpyxfdfenfcerylfdfepn xkczufszwanyfdfeacjbsdfryxhhnfsebsd
fjhnfcwwefwchfylyxetypczrjxllfeszwh nyxjczrjyloybiwvcbzdcmwgwsbawvcsmsg
wcanbvcksbsjwkvskzdwbcacfcdtrpbzcdn bvisdngcdcfcdtrcdsnbvksyndvcfcdtkdc
nzsdnbvvcazdstcdsikwfwmwunzwsbcfcdt xwbgnbvhcnanbzcfcdttspbgksphmcwbmsf
ccfcdtjszrcdnbvinzrcdrshscgbwudbydo fsoikpqoysejbkpspsfspzisqwuspkctkpq
brsfspzwkppgjijkbdidwdqosfspzrgjspr iqpsfspzrgjpstsbsqyspsfspzrqdoiqoyr
doospdoiusudrikpzkckgprjswdsrbdfsyi uspskoqtkiskcygrirgrjsoysydoqrgonsqt
"""
